const servicesData = [
    { 
        title: "Interpersonal Skills",
        category: "frontend",
        description: ['In my college projects and at Tufts Health Plan, I have really learned into a bunch of soft skills that I think have made a big difference:', 'First up, detail-oriented. When I was working on the Artificial Intelligence Virtual Keyboard and Responsive Portfolio Website projects, paying attention to the nitty-gritty was crucial. It is all about making sure the code runs smoothly and users get the best experience. Then there is documentation. I have always made it a point to create clear and thorough documentation for my projects. It is like leaving a roadmap for myself and others, and it is been a game-changer for keeping everything organized. Communication is another strong suit. In my role as an Information Systems Specialist at Tufts Health Plan, I was tackling security, network, and software-related issues. Being able to explain complex tech stuff in a way that makes sense to everyone is key, and I have found that it is helped a lot in troubleshooting. Problem-solving is my jam. Whether it is resolving incidents daily at Tufts Health Plan or ironing out bugs in my projects, I love diving into problems, figuring out what going on, and finding solutions. It keeps things interesting!','Troubleshooting at Tufts Health Plan was like being a tech detective, requiring quick thinking to diagnose and fix security and software issues. Mastering time management was essential, particularly with project deadlines and user access responsibilities. As a team player, whether collaborating with faculty on projects or working at Tufts Health Plan, I understand the importance of bringing diverse perspectives together for successful outcomes.'
            ]
    },

    { 
        title: "Coding Experience",
        category: "backend",
        description: ['I possess a robust foundation in computer science, as evidenced by my completion of an Associate of Science in Computer Science at Quinsigamond Community College, with a 3.7 GPA. This education equipped me with a strong understanding of calculus, discrete mathematics, programming languages, operating systems, and data structures.','Currently pursuing a Bachelor of Science in Computer Science with a concentration in Information Systems at Framingham State University, I maintain a 3.8 GPA. This program has deepened my knowledge in computer architecture, algorithms, and user-friendly web programming, contributing to a well-rounded technical skill set.','I am fluent in a variety of programming languages, including C++, SQL, HTML, CSS, Python, Java, and JavaScript. Furthermore, I am actively working towards becoming an AWS Cloud Practitioner, reflecting my commitment to staying at the forefront of cloud computing technologies.','My proficiency extends to development tools such as Android Studios, Apache Netbeans, and GitHub, and I am adept at operating in both Unix/Linux and Windows environments. The completion of projects like the Artificial Intelligence Virtual Keyboard and Responsive Portfolio Website demonstrates my ability to apply these technical skills to create innovative and functional solutions.'
            ]
    },

    { 
        title: "Technical Qualifications",
        category: "fullstack",
        description: ['In both my academic and professional experiences, I have demonstrated a high level of proficiency in various programming languages and development tools. During my time at Quinsigamond Community College, I acquired a strong foundation in programming languages such as C++, equipping me with the skills to tackle complex problem-solving scenarios. This foundation was further expanded upon at Framingham State University, where I delved into languages like Python, Java, and JavaScript, enhancing my versatility in software development.', 'I am pleased to announce the successful completion of the AWS Cloud Practitioner course, underscoring my dedication to staying at the forefront of cloud computing technologies. This achievement reflects not only a comprehensive understanding of AWS services and best practices but also a commitment to leveraging cloud solutions for enhanced efficiency and scalability in the ever-evolving field of computer science.','In my current role as an Information Systems Specialist at Tufts Health Plan, I utilize programming skills to address security, network, and software-related issues. This role demands proficiency in languages such as PowerShell, emphasizing my adaptability in using diverse tools for effective problem resolution.','Overall, my programming skills, honed through academic coursework and hands-on projects, position me as a versatile and adept professional in the field of computer science.'
            ]
    }

]